sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AaQJxCMTOYj6O/KFW5CWLLn/HV5S3JClfEBHqdnKjtfm3FksIT5V643nx5P6uIwiYOr7c2S/Ocq6HOQ7dwNMVqJ3cHJbk0SkUcfadj+NP4aEdL/yDmhrzL2kD1WC7vHqSCfu70ZW0YV8OABEuY0JMzjbam5jHulO5TQY4KZexS79s9qxLZxC7Z5Yw8HaHCf2HhW5R6S/66w9308BOdd+oNTgQoI/aFKxarw25uTnIYk/GWxxV/lYa/2jMCi54xmmlFjApUIozCjDi9Ok7j7T15PR11j0ggDlhMognaXOWGCJUPpHxsZfwjXX9Iwn2cHTt5VQTkRP2OTgrNX8aZg4lySYKNKVAJoGEjUtn9g09XTvJGmJ3suHkFSJOabhjfbCLlqmmrBagrECng9YciSEwwJp3t14WXfmobBNPtt9PQwkFAq9Wf52SafzatnJi4T/FUbkJFFNLxb3jSjk+x2Dszkx/YQoZammioheZGazjr5dHHXGbU0F/ZSVxmg92dOxDeyiuRDOSysuZ9PL8mu7ho3sJwXZmVKD8eUVfOtcZKWXcwNbSQR/T+O9Br0pHM2Inu6NSRNQFh9UL3NpPsp3l+fVQW1cnQFOtClukvmP9TkXGOJSp27arbq6jxkJPoECxS9BznglwS4iNwSHeWv3vRK4kJjBZ+MTxELei2tM+OU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/In-Defense-of-Women_1270
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy